### ISSUE TITLE
The prediction result of predictor which was from export_savedmodel is different from the result from model.predict()

### ISSUE THREAD

**Issue by DJofOUC** [AshutoshDongare/Tensorflow-Wide-Deep-Local-Prediction#1]
When I use model.predict(),the probability is (0.442,0.558).however,the probability is (0.421,0.579)  when using tf.contrib.predictor.from_saved_model().why the probability is different,I use the same sample

**Comment by AshutoshDongare** [comment]
Given that all other conditions the same, this could be because I am using only DeepColumns while saving the model definition whereas model.predict() would be using both Wide and Deep columns definition..Just trying to guess the difference.

'''Export Trained Model for Serving'''
  wideColumns, DeepColumns = build_model_columns()
  **feature_columns = DeepColumns**
  feature_spec = tf.feature_column.make_parse_example_spec(feature_columns)
  export_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
  servable_model_dir = "/tmp/census_exported"
  servable_model_path = model.export_savedmodel(servable_model_dir, export_input_fn)
  print("*********** Done Exporting at PAth - %s", servable_model_path )
